service: my-service # NOTE: update this with your service name

plugins:

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
    environment:
      MONGODB_URI: ${cf:${self:service}-${self:provider.stage}.ClusterSrvAddress} 
      MONGODB_PWD: ${cf:${self:service}-${self:provider.stage}.DBPassword} 
      MONGODB_USER: ${cf:${self:service}-${self:provider.stage}.DBUsername} 

custom:
  PublicKey: ${env:ATLAS_PUBLIC_KEY}   
  PrivateKey: ${env:ATLAS_PRIVATE_KEY} 
  OrgId: ${env:ATLAS_ORG_ID}
  ProjectName: "aws-node-mongodb-atlas-cfn" 
  ClusterInstanceSize: "M2"
  ClusterRegion: "us-east-1"
  ClusterName: "Cluster-1"

resources:
  Parameters:
    PublicKey:
      Description: "Your MongoDB Cloud Public API Key"
      Type: String
      Default: ${self:custom.PublicKey}
    PrivateKey:
      Description: "Your MongoDB Cloud Private API Key"
      Type: String
      Default: ${self:custom.PrivateKey}
    OrgId:
      Description: "Your MongoDB Cloud Organization Id"
      Type: String
      Default: ${self:custom.OrgId}
    ProjectName:
      Description: "The name of the project."
      Type: String
      Default: ${self:custom.ProjectName}
    ClusterName:
      Description: Name of the cluster as it appears in Atlas. Once the cluster is created,
        its name cannot be changed.
      Type: String
      Default: ${self:custom.ClusterName}
    ClusterInstanceSize:
      Default: ${self:custom.ClusterInstanceSize}
      Description: Atlas provides different cluster tiers, each with a default storage capacity and RAM size. The cluster you select is used for all the data-bearing hosts in your cluster tier. See https://docs.atlas.mongodb.com/reference/amazon-aws/#amazon-aws.
      Type: String
      AllowedValues:
      - "M2"
      - "M5"
      - "M10"
      - "M20"
      - "M30"
      - "M40"
      - "R40"
      - "M40_NVME"
      - "M50"
      - "R50"
      - "M50_NVME"
      - "M60"
      - "R60"
      - "M60_NVME"
      - "M80"
      - "R80"
      - "M80_NVME"
      - "M100"
      - "M140"
      - "M200"
      - "R200"
      - "M200_NVME"
      - "M300"
      - "R300"
      - "R400"
      - "M400_NVME"
      - "R700"
    ClusterRegion:
      Default: ${self:custom.ClusterRegion}
      Description: The AWS Region where the Atlas DB Cluster will run.
      Type: String
      AllowedValues:
      - "us-east-1"
      - "us-east-2"
      - "ca-central-1"
      - "us-west-1"
      - "us-west-2"
      - "sa-east-1"
      - "ap-south-1"
      - "ap-east-2"
      - "ap-southeast-1"
      - "ap-southeast-2"
      - "ap-northeast-1"
      - "ap-northeast-2"
      - "eu-central-1"
      - "eu-west-1"
      - "eu-north-1"
      - "eu-west-1"
      - "eu-west-2"
      - "eu-west-3"
      - "eu-south-1"
      - "me-south-1"
      - "af-south-1"
    ClusterMongoDBMajorVersion:
      Description: The version of MongoDB
      Type: String
      Default: "4.4"
      AllowedValues:
      - "3.6"
      - "4.0"
      - "4.2"
      - "4.4"
    DatabaseUserUsername:
      Description: Database User Username
      Type: String
      Default: "get-started-aws-sam"
    DatabaseUserPassword:
      Description: Database User Password
      Type: String
      Default: "CZtUvvkMGSXXJBsW"
    DatabaseUserRoleDatabaseName:
      Description: Database User Role Database Name
      Type: String
      Default: "test"
  Resources:
    AtlasProject:
      Type: MongoDB::Atlas::Project
      Properties:
        OrgId: !Ref "OrgId" 
        ApiKeys:
          PublicKey:  !Ref "PublicKey"
          PrivateKey: !Ref "PrivateKey"
        Name: !Ref "ProjectName"
    AtlasProjectIPAccessList:
      Type: MongoDB::Atlas::ProjectIpAccessList
      DependsOn: AtlasProject
      Properties:
        ProjectId: !Ref "AtlasProject"
        ApiKeys:
          PublicKey:  !Ref "PublicKey"
          PrivateKey: !Ref "PrivateKey"
        AccessList:
        - IPAddress: "0.0.0.0/0"
          Comment: "Testing open all ips"
    AtlasDatabaseUser:
      Type: MongoDB::Atlas::DatabaseUser
      DependsOn: AtlasProject
      Properties:
        ProjectId: !Ref "AtlasProject"
        ApiKeys:
          PublicKey:  !Ref "PublicKey"
          PrivateKey: !Ref "PrivateKey"
        #Username: !GetAtt "AtlasIAMRole.Arn"
        Username: !Ref "DatabaseUserUsername"
        Password: !Ref "DatabaseUserPassword"
        #DatabaseName: "$external"
        DatabaseName: "admin"
        #AWSIAMType: "ROLE"
        Roles:
        - RoleName: "readWriteAnyDatabase"
          DatabaseName: "admin"
        Scopes:
        - Name: !Ref "ClusterName"
          Type: "CLUSTER"
    AtlasCluster:
      Type: MongoDB::Atlas::Cluster
      DependsOn: AtlasProject
      Properties:
        ApiKeys:
          PublicKey:  !Ref "PublicKey"
          PrivateKey: !Ref "PrivateKey"
        ProjectId: !Ref "AtlasProject"
        Name: !Ref "ClusterName"
        MongoDBMajorVersion: !Ref "ClusterMongoDBMajorVersion"
        ReplicationFactor: 3
        NumShards: 1
        ProviderSettings:
          ProviderName: "AWS"
          InstanceSizeName: !Ref "ClusterInstanceSize" 
          RegionName: !Ref "ClusterRegion"
  Outputs:
    DBUsername:
      Description: "Hostname for mongodb+srv:// connection string"
      Value: !Ref "DatabaseUserUsername"
      #Export:
      #  Name: ${self:service}:${self:provider.stage}.DBUsername
    DBPassword:
      Description: "Hostname for mongodb+srv:// connection string"
      Value: !Ref "DatabaseUserPassword"
      #Export:
      #  Name: ${self:service}:${self:provider.stage}.DBPassword
    ClusterSrvAddress:
      Description: "Hostname for mongodb+srv:// connection string"
      Value: !GetAtt "AtlasCluster.SrvAddress"
      #Export:
      #  Name: ${self:service}:${self:provider.stage}.ClusterSrvAddress
  
